# Generated by Django 4.1.4 on 2022-12-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_user_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
