# Generated by Django 4.1.4 on 2022-12-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_rename_author_id_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttag',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='posttag',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
